discourse_vip_badge:
  vip_badge_enabled:
    client: true
    default: true
    type: bool
  vip_badge_show_on_profile:
    client: true
    default: false
    type: bool
  vip_badge_group_names:
    client: true
    default: ""
    type: group_list
    allow_any: false  # For choice settings allow items not specified in the choice list (default true)
    refresh: false    # Set to true if clients should refresh when the setting is changed.
  vip_badge_use_group_name:
    client: true
    default: false
    type: bool
  vip_badge_text:
    client: true
    default: "VIP"
    type: string
  vip_badge_icon:
    client: true
    default: "crown"
    type: string
  vip_badge_visibility:
    client: true
    default: "staff"
    type: enum
    choices:
      - all
      - has trust level
      - is staff or has trust level
      - is staff
      - is staff and has trust level
  vip_badge_visibility_min_trust_level:
    client: true
    default: "4"
    type: enum
    choices:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
