discourse_vip_badge:
  vip_badge_enabled:
    client: true
    default: true
    type: bool
  vip_badge_show_on_profile:
    client: true
    default: false
    type: bool
  vip_badge_use_group_name:
    client: true
    default: false
    type: bool
  vip_badge_visibility:
    client: true
    default: "staff"
    type: enum
    choices:
      - all
      - has trust level
      - is staff or has trust level
      - is staff
      - is staff and has trust level
  vip_badge_visibility_min_trust_level:
    client: true
    default: "4"
    type: enum
    choices:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"

  # I wanted to use objects here, but site settings doesn't support that well enough yet
  # https://meta.discourse.org/t/objects-type-for-theme-setting/305009
  vip_badge_bronze_groups:
    client: true
    default: ""
    type: group_list
    allow_any: false
    refresh: false
  vip_badge_bronze_text:
    client: true
    default: "Bronze VIP"
    type: string
  vip_badge_bronze_icon:
    client: true
    default: "medal"
    type: string

  vip_badge_silver_groups:
    client: true
    default: ""
    type: group_list
    allow_any: false
    refresh: false
  vip_badge_silver_text:
    client: true
    default: "Silver VIP"
    type: string
  vip_badge_silver_icon:
    client: true
    default: "star"
    type: string

  vip_badge_gold_groups:
    client: true
    default: ""
    type: group_list
    allow_any: false
    refresh: false
  vip_badge_gold_text:
    client: true
    default: "Gold VIP"
    type: string
  vip_badge_gold_icon:
    client: true
    default: "crown"
    type: string
